// Generated by Wrangler by running `wrangler types`

interface Env {
	ARTICLE_CACHE: KVNamespace;
	RESEND_KEY: string;
	FROM_EMAIL: string;
	BROWSER_CONTROLLER: DurableObjectNamespace<import("./src/index").BrowserController>;
	BROWSER: Fetcher;
	ASSETS: Fetcher;
	WORKFLOW: Workflow;
}
