// Generated by Wrangler by running `wrangler types`

interface Env {
	PDF_CACHE: KVNamespace;
	RESEND_KEY: string;
	FROM_EMAIL: string;
	BROWSER_CONTROLLER: BrowserController;
	BROWSER: Fetcher;
	WORKFLOW: Workflow;
}
